<?php

namespace App\Models;

use App\Observers\ApiuserObserver;
use GuzzleHttp\Client;
use Laravel\Passport\HasApiTokens;
use Illuminate\Foundation\Auth\User as Model;
use App\Models\Traits\Btn;
class Apiuser extends Model
{
    use HasApiTokens,Btn;
    protected $hidden=['password'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::observe(ApiuserObserver::class);
    }

    //Guzzle请求
    public static function get($url){
        $client=new Client([
            'timeout'=>5,
            'verify'=>false
        ]);

        $ret=$client->get($url);
        $json=(string)$ret->getBody();
        return json_decode($json,true);
    }
}

